- name: Deploy Helm chart for the application
  hosts: all
  tasks:
    - name: Set up environment variables
      shell: |
        export POSTGRES_DB=customer_order_service
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=2024Savannah
        export DJANGO_SECRET_KEY=django-insecure-$qfi93p0%m_2%6!3xc)o(i%wlgp-ftup91t&47*te=-b!yr6zu

    - name: Deploy Helm chart
      shell: helm upgrade --install customer-order-service ./helm

- name: Run database migrations
  hosts: all
  tasks:
    - name: Run Django migrations
      shell: |
        kubectl exec -it $(kubectl get pods -l app=customer-order-service -o jsonpath="{.items[0].metadata.name}") -- python manage.py migrate
