openapi: 3.0.3
info:
  title: CUSTOMER_ORDER APIS
  version: 1.0.0
  description: CO SYSTEM
paths:
  /api/register/:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  email:
                    type: string
        '400':
          description: Bad request

  /api/login/:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized

  /api/orders/:
    get:
      summary: List all orders
      security:
        - jwtAuth: []
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /api/orders/create/:
    post:
      summary: Create a new order
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: string
                amount:
                  type: number
              required:
                - item
                - amount
      responses:
        '201':
          description: Order created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized

  /api/orders/{pk}/:
    get:
      summary: Retrieve an order
      security:
        - jwtAuth: []
      parameters:
        - name: pk
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
        '401':
          description: Unauthorized

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
        customer_details:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
        item:
          type: string
        order_number:
          type: string
        amount:
          type: number
        status:
          type: string
        created_at:
          type: string
          format: date-time

  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    oauth2:
      type: oauth2
      flows: {}
